<a href="https://colab.research.google.com/github/IamBhanuYenumula/Byen_DataScience_expo/blob/main/Covariance_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from sklearn.datasets import load_iris

# load the Iris dataset
iris = load_iris()
X =iris.data
m,n = X.shape

# calculate the mean vector
X_mean = np.mean(X,axis = 0)

# Center the data matrix
X_centered = X - X_mean

##Calculate the covariance matrix
C = np.dot(X_centered.T,X_centered) / (m - 1)

#Display covariance matrix:
print("\n Covariance Matrix:")
print(C)


 Covariance Matrix:
[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]
